pr #2 from ms/master (#2)
* Make requested changes to Mzalendo menu items.

* Remove "Data" and "Newsletter" items
* Add appropriate redirects
* Remove "Public Participation"
* Reshuffle existing "Research" items

* Prevent Featured Person title disappearing when switching next/prev

* [KE] Move Featured Person carousel to top right of homepage

Fixes #2303.

* Use a Google Maps Geocoding API key if supplied in general.yml

We have been getting lots of:

   GeocoderError: Error OVER_QUERY_LIMIT

... errors from pombola/search/geocoder.py, which we should deal with by
paying for usage of the API. This requires using an an API key to
identify us, hence this change.

* ssh to the remote server and run pg_dump there

Our public database dumps are failing because of a version mismatch
between pg_dump and the version of PostgreSQL on the server. If the HOST
database setting indicates that the database is on a remote host, the
command will now be prefixed by 'ssh <hostname>'.

* Fix URLs for Pombola install in install-as-user

- pa.org.za now runs off https
- ShineYourEye is now a static site, so refer to the old pombola version

* Fixes #2319 Bonga-Na-Mzalendo and the Dokeza buttons swapped.

* [ZA] Select correct person page tab on pageload

Loading a person page with the ID of a tab in the URL hash fragment
will now automatically reveal that tab, as you would expect.

* [KE] Add new "Responsibilities" to Positions, and display in profiles.

Part of #2304.

* Add lists of women reps and young reps.

Women is generated from the database (people tagged "female"), young reps
is a hard-coded list of positions.

Closes #2314