Use a Google Maps Geocoding API key if supplied in general.yml
We have been getting lots of:

   GeocoderError: Error OVER_QUERY_LIMIT

... errors from pombola/search/geocoder.py, which we should deal with by
paying for usage of the API. This requires using an an API key to
identify us, hence this change.