merge updates from ms/pombola (#1)
* Make requested changes to Mzalendo menu items.

* Remove "Data" and "Newsletter" items
* Add appropriate redirects
* Remove "Public Participation"
* Reshuffle existing "Research" items

* Prevent Featured Person title disappearing when switching next/prev

* [KE] Move Featured Person carousel to top right of homepage

Fixes #2303.

* Use a Google Maps Geocoding API key if supplied in general.yml

We have been getting lots of:

   GeocoderError: Error OVER_QUERY_LIMIT

... errors from pombola/search/geocoder.py, which we should deal with by
paying for usage of the API. This requires using an an API key to
identify us, hence this change.